---
title: "Anomaly Detection"
author: "Joe Kirika"
date: "15/07/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing And Previewing The Data                 
### Importing the data

```{r}
# calling the necessary libraries
library(tidyverse)
library(anomalize)
library(tibbletime)
library(dplyr)
```

```{r}
df4 <- 'http://bit.ly/CarreFourSalesDataset' 
```
          
```{r}
# Grouping by server and converting to tibbletime

sales <- read.csv(df4) %>% group_by(Date) %>%
   mutate(Date = as.Date (Date, format="%m/%d/%Y")) %>% as_tbl_time(index = Date)

head(sales)

```

```{r}
# performing anomaly detection on the sales 
sales_anomalized <- sales %>% summarise(Orders = sum(Sales)) %>%
    time_decompose(Orders) %>%
    anomalize(remainder, alpha = 0.05, max_anoms = 0.2) %>%
    time_recompose() %>%
    plot_anomalies(time_recomposed = TRUE) +
    ggtitle("alpha = 0.05, max_anoms = 0.2")
    
sales_anomalized
```
                                                  
                                                        
> using the default values for alpha and max-anoms would not show the anomalies


```{r}
# adjusting the alpha value (increaing the alpha value) then performing anomaly detection on the sales  
sales_anomalized <- sales %>% summarise(Orders = sum(Sales)) %>%
    time_decompose(Orders) %>%
    anomalize(remainder, alpha = 0.2, max_anoms = 0.2) %>%
    time_recompose() %>%
    plot_anomalies(time_recomposed = TRUE) +
    ggtitle("alpha = 0.2, max_anoms = 0.2")
    
sales_anomalized
```
                                                    
                                                    
> with alpha = 0.2 and max_anoms = 0.2 we can observe some outliers with observed > 7000


